service: auth-demo-api

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-1
  stage: ${env:STAGE,'development'}
  environment:
    STAGE: ${self:provider.stage}

functions:
  auth:
    handler: ./src/handler.handler
    events:
       - http:
          path: /{proxy+}
          method: any
      

plugins:
  - serverless-offline
  - serverless-plugin-typescript